# Generated by Django 2.2.5 on 2020-12-21 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='has_point',
            field=models.BooleanField(default=False, verbose_name='ポイント機能を使用する'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='has_stamp',
            field=models.BooleanField(default=False, verbose_name='スタンプ機能を使用する'),
        ),
        migrations.CreateModel(
            name='PointCardLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='time')),
                ('date', models.DateField(verbose_name='date')),
                ('action', models.CharField(max_length=10, null=True, verbose_name='action')),
                ('point', models.IntegerField(blank=True, null=True)),
                ('number_of_stamps', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Customer', verbose_name='customer')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Shop', verbose_name='shop')),
            ],
        ),
    ]
