# Generated by Django 3.1.2 on 2020-12-01 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='has_point',
            field=models.BooleanField(default=False, help_text='ユーザがポイントカードを作成したときにそのポイントカードがポイントカード機能を使用するか', verbose_name='ポイント機能を使用する'),
        ),
        migrations.AddField(
            model_name='shop',
            name='has_stamp',
            field=models.BooleanField(default=False, help_text='ユーザがポイントカードを作成したときにそのポイントカードがポイントカード機能を使用するか', verbose_name='スタンプ機能を使用する'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='年齢'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, '男性'), (2, '女性'), (3, 'その他')], null=True, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='苗字'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(max_length=150, verbose_name='店舗名'),
        ),
    ]
