# Generated by Django 2.2.5 on 2020-10-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True, verbose_name='age'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[('man', '男性'), ('woman', '女性'), ('other', 'その他')], null=True, verbose_name='sex'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(max_length=20, null=True, verbose_name='username'),
        ),
    ]
