# Generated by Django 3.1.2 on 2020-10-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201020_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name=' age '),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(blank=True, choices=[('man', '男性'), ('woman', '女性'), ('other', 'その他')], null=True, verbose_name=' sex '),
        ),
    ]
