# Generated by Django 3.1.2 on 2020-11-11 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20201110_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer', verbose_name='customer')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'point card',
                'verbose_name_plural': 'point cards',
            },
        ),
        migrations.CreateModel(
            name='NumericalPointCard',
            fields=[
                ('pointcard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.pointcard')),
                ('point', models.IntegerField(verbose_name='point')),
            ],
            bases=('account.pointcard',),
        ),
        migrations.CreateModel(
            name='StampPointCard',
            fields=[
                ('pointcard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.pointcard')),
                ('num_of_stamps', models.IntegerField(verbose_name='number of stamps')),
            ],
            bases=('account.pointcard',),
        ),
    ]
